#!/bin/bash


if [ "$#" = 1 ] && [ "$1" = "build" ]; then
    echo "Building workspace."

    if [ ! -d "web/node_modules" ]; then
        cd web
        npm ci
        cd ..
    fi

    cd ros && catkin build


elif [ "$#" = 1 ] && [ "$1" = "clean" ]; then
    echo "Cleaning workspace."
    rm -r ros/build ros/devel ros/logs ros/.catkin_tools web/node_modules


elif [ "$#" = 1 ] && [ "$1" = "start_robot" ]; then
    echo "Starting."

    source ros/devel/setup.bash
    roslaunch platypous_launch main.launch &

    if [ -d "web/node_modules" ]; then
        cd web && node server.js &
    fi

    wait


elif [ "$#" = 1 ] && [ "$1" = "start_sim" ]; then
    echo "Starting."

    source ros/devel/setup.bash
    roslaunch platypous_launch simulation.launch &

    if [ -d "web/node_modules" ]; then
        cd web && node server.js &
    fi

    wait

else
    echo "Starting BASH shell. PlatypOUs workspace sourced."
    source ros/devel/setup.bash
    bash
    echo "Exit PlatypOUs workspace BASH."
fi
