#!/bin/bash

if [ "$#" = 1 ] && [ "$1" = "build" ]; then
    
    if [ ! -d "web/node_modules" ]; then
        cd web && npm ci && cd ..
    fi

    cd ros && catkin build

elif [ "$#" = 1 ] && [ "$1" = "start" ]; then

    source ros/devel/setup.bash

    roslaunch platypous_launch simulation.launch &
    sleep 2 && cd web && node server.js &

    wait

else
    echo ""
    echo "    Wrong/no argument. Usage: ./platypous_sim [option]"
    echo ""
    echo "      Please choose one of the following options:"
    echo ""
    echo "        build:          builds the ROS workspace and initializes the"
    echo "                        web server dependencies"
    echo "        start:          starts the simulation with the default parameters"
    echo "                        and the web server"
    echo ""
    echo "      for example: ./platypous_sim start"
    echo ""
fi
