name: Docker Image CI

on:
  push:
    branches: [ devel ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: /bin/bash build_image.bash
